version: '3.6'
# Use this docker-compose file with nginx-proxy.
services:
  informix:
    container_name: informix
    build:
      context: ./
      target: php_apache_pdo_informix_dev
    volumes:
      - ./src:/var/www/html
    expose:
      - 80
    environment:
      - INFORMIX_HOST=${INFORMIX_HOST}
      - INFORMIX_PORT=${INFORMIX_PORT}
      - INFORMIX_DB=${INFORMIX_DB}
      - INFORMIX_SERVER=${INFORMIX_SERVER}
      - INFORMIX_PROTOCOL=${INFORMIX_PROTOCOL}
      - INFORMIX_SCROLCURS=${INFORMIX_SCROLCURS}
      - INFORMIX_USER=${INFORMIX_USER}
      - INFORMIX_PASSWORD=${INFORMIX_PASSWORD}
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=informix.local

networks:
  default:
    external:
      name: nginx-proxy