version: '3.6'

services:
  informix:
    container_name: informix
    build:
      context: ./
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    environment:
      - INFORMIX_HOST=${INFORMIX_HOST}
      - INFORMIX_PORT=${INFORMIX_PORT}
      - INFORMIX_DB=${INFORMIX_DB}
      - INFORMIX_SERVER=${INFORMIX_SERVER}
      - INFORMIX_PROTOCOL=${INFORMIX_PROTOCOL}
      - INFORMIX_SCROLCURS=${INFORMIX_SCROLCURS}
      - INFORMIX_USER=${INFORMIX_USER}
      - INFORMIX_PASSWORD=${INFORMIX_PASSWORD}